### ISSUE TITLE
messpunkte

### ISSUE THREAD

**Issue by aribaer** [Arkinator/Hupe#10]
wenn das die vorstellung "wünsch dir was" ist, dann könnte man noch die Messpunkte (auswählbar) durch kleine Karos darstellen.

**Comment by aribaer** [comment]
das mit den messpunkten ist vermutlich quatsch, weil man in der regel einen tag misst und dann hat man tägiich 205 messungen das ist gar nicht mehr sichtbar und interessant

**Comment by Arkinator** [comment]
Close fehlt
