### ISSUE TITLE
sets

### ISSUE THREAD

**Issue by aribaer** [Arkinator/Hupe#11]
wir binden ja messsets, also immer fünf (oder so) messgerät messen gleichzeitig in einem haus und werden auch zeitlich parallel ausgewertet. 
also wäre es schön, wenn man nicht alle sieben datenfiles für jede auswertung aufs neue eingeben muss fürs  importieren, weil nämlich dieselben kurven auf demselben rechner immer an der gleichen stelle liegen. 
also sollte man die sets einmal importieren und dann die importparameter speichern können, 

beim nächsten hupe aufruf kann man dann fürs selbe set wählen und bekommt dann automatisch dieselben messwerte importiert, allerdings können die messdaten inzwischen überschrieben worden sein, weil eine mail mit neuen daten kam, die die alten messwerte überschrieben haben....klar??

**Comment by Arkinator** [comment]
Geschlossen nach Rücksprache
