### ISSUE TITLE
strichstärke

### ISSUE THREAD

**Issue by aribaer** [Arkinator/Hupe#20]
die änderung der voreingestellten strichstärke ist sehr mühsam, bitte mal selbst ausprobieren, vielleicht auch ein bedienfehler meinerseits.

**Comment by Arkinator** [comment]
Was meinst du mit mühsam? Du machst einen doppelklick auf die Zelle und trägst die Zahl ein. Ich hab noch eine Combo-Box eingefügt, welche ein paar Default-Werte bereit hält
